# Dependencies
kramdown:
  input: GFM
#markdown: redcarpet

highlighter: rouge

#:         true

# Permalinks
permalink:        pretty

# Setup
title:            Holy Cross Digital Diplomatic Editions
tagline:          ''
description:      ''

baseurl: ''

author:
  name:           'Neel Smith'

paginate:         5


# Links:
links:
  - title: Home
    url: /
  - title: Guidelines
    url: /guidelines
  - title: Data repository
    url: https://github.com/hc-dde/editions/
    external: true
